
services:
  postgres:
    container_name: "guess_cat_db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_DB=guess_cat"
